### ISSUE TITLE
Default capabilities

### ISSUE THREAD

**Issue by victor4pinheiro** [Saghen/blink.cmp#13]
I added this plugin to my config and although I only use the basic completions, a little thing surprised me.
When using nvim-cmp, to broadcast to servers, we're supposed to do something like that:
```
local capabilities = require('cmp_nvim_lsp').default_capabilities()

  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
  require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
    capabilities = capabilities
  }
```
But I see that this plugin doesn't need it (or I believe it's not needed). My first thoughts is that while all plugins that use LSP broadcast to servers that use the native vim.lsp and this plugin just use the results of this.

Could you explain what is the difference and why I don't need to do this anymore, please?

**Comment by Saghen** [comment]
Capabilities tell the LSP which features the client supports. `nvim-cmp` uses this since it supports many features that the built-in vim.lsp did not (and some that still aren't). Many capabilities have been enabled by default since that plugin was written. So far, I've been using [the defaults](https://github.com/neovim/neovim/blob/385fbfb3e739b457027b469782678f86eefdf7fc/runtime/lua/vim/lsp/protocol.lua#L443) but will likely need to adopt this in the future

**Comment by victor4pinheiro** [comment]
Thanks for answer!

**Comment by chrisgrieser** [comment]
I gave this a try, and both cmp and blink.cmp work in most LSPs without the `capabilities` snippet. However, for the css_ls, both plugin do require the `capabilities` snippet to work.

**Comment by kryptamine** [comment]
+1, css_ls completion is not working

**Comment by chrisgrieser** [comment]
@kryptamine for css_ls, you need to add this snippet:
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
require("lspconfig").css_ls.setup({
	capabilities = capabilities
})
```

**Comment by kryptamine** [comment]
Thanks a lot!

**Comment by chrisgrieser** [comment]
@Saghen Just a heads up, the snippet added in 708a4a9 does not work, since `opts.servers` is nil.
