### ISSUE TITLE
Include words from other buffers

### ISSUE THREAD

**Issue by kaiphat** [Saghen/blink.cmp#190]
https://github.com/user-attachments/assets/90ede5d8-644e-4bbc-b333-8949036bf02d

Expected: there are text completions from another buffers

**Comment by farzadmf** [comment]
Hey guys;

Is "all buffers" supposed to be the default? Asking because I don't seem to see words from my other buffers.

I don't see anything related to buffers in the README, and checking the [docs (sources section)](https://cmp.saghen.dev/configuration/sources.html) doesn't mention anything either.

**Comment by Saghen** [comment]
Hey, a recipe for it was added in the v0.11.0 release that just went out: https://cmp.saghen.dev/recipes#buffer-completion-from-all-open-buffers

**Comment by farzadmf** [comment]
@Saghen Great! Appreciate the fast response. Keep up the amazing work!
