### ISSUE TITLE
Different behavior appears in neovim nightly and stable version

### ISSUE THREAD

**Issue by Parsifa1** [Saghen/blink.cmp#423]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

release:
![recording](https://github.com/user-attachments/assets/33e67b77-669f-4daf-8ddc-4f6e8a40653e)

nightly:

https://github.com/user-attachments/assets/0fef5ef0-16d5-4a1e-9766-3fb5f9f7c12a

is there any wrong with the `vim.snippet` api in the nightly neovim or in the blink.cmp?

### neovim version

`nightly` vs. `release`

### `blink.cmp` version: branch, tag, or commit

`main`

**Comment by Parsifa1** [comment]
it seems that if i set `opts.snippets.expand` to `nil`, the args wont expand and i will get what i want :) 
![image](https://github.com/user-attachments/assets/31e5d291-48e9-43ba-bd5d-86efd8d6e2d5)

**Comment by Saghen** [comment]
Neither of these seem incorrect, but rather, it looks like the LSP returns snippet completion items only nightly, potentially due to this change: https://github.com/neovim/neovim/compare/v0.10.2...nightly#diff-a12755025a01c2415c955ca2d50e3d40f9e26df70f712231085d3ff96b2bc837R460

You might want to check that you have this capabilities snippet from the [installation section](https://github.com/Saghen/blink.cmp?tab=readme-ov-file#installation). If you want to disable the snippets, you could override the `snippetsSupport = true` piece before passing it to lspconfig
