### ISSUE TITLE
Misplacement of signature help window

### ISSUE THREAD

**Issue by arztareef** [Saghen/blink.cmp#690]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

![image](https://github.com/user-attachments/assets/a2825813-3a9e-44bb-a756-7c2cbb13e707)
![image](https://github.com/user-attachments/assets/7e89788f-0036-4efc-853f-6387ccf4f1a6)

signature help window is placed at the _top of the screen_ even when there is considerable amount of space below it.
(the `south` priority should take over)

### Relevant configuration

```lua
--- (using the default config with some tweaks to the icons and keymaps)
```

### neovim version

NVIM v0.11.0-dev-1388+g39781be14b

### `blink.cmp` version: branch, tag, or commit

v0.*

**Comment by Saghen** [comment]
The window placement code is quite complicated because it needs to deal with 3 potentially overlapping windows. I ended up placing the signature help on the opposite side from the menu to guarantee they won't overlap. This seems like a rare case and you can still read the function signature, just not the documentation, so I think I'll leave it as is
