### ISSUE TITLE
No docstring snippet completion

### ISSUE THREAD

**Issue by idnsunset** [Saghen/blink.cmp#758]
### Make sure you have done the following

- [X] I have updated to the latest version of `blink.cmp`
- [X] I have read the README

### Bug Description

I set `sources.providers.snippets.opts.exteneded_filetypes` to enable docstring snippet completion, but got no completion at all. The similar configuration with `nvim-cmp` and `nvim-snippets` works well. Not sure if this is the problem with my configuration or `blink.cmp` itself.

### Relevant configuration

Configuration with `lazy.nvim`:

```lua
opts = {
  -- ...
  sources = {                                                        
    compat = {},                                                     
    default = { "lsp", "path", "snippets", "buffer" },               
    cmdline = {},                                                    
    providers = {                                                    
      snippets = {                                                   
        opts = {                                                     
          friendly_snippets = true,                                  
          search_paths = { vim.fn.stdpath("config") .. "/snippets" },
          global_snippets = { "all" },                               
          extended_filetypes = {                                     
            c = { "cdoc" },                                          
            cpp = { "cppdoc" },                                      
            lua = { "luadoc" },                                      
            python = { "pydoc" },                                    
            rust = { "rustdoc" },                                    
            sh = { "shelldoc" },                                     
          },                                                         
          ignored_filetypes = {},                                    
          get_filetype = function(ctx)                               
            return vim.bo.filetype                                   
          end,                                                       
        },                                                           
      },                                                             
    },                                                               
  },                                                                 
  -- ...
},
```

### neovim version

NVIM v0.10.2

### `blink.cmp` version: branch, tag, or commit

v0.8.2

**Comment by Saghen** [comment]
Do you have `friendly-snippets` as a dependency?

**Comment by dpetka2001** [comment]
Why is the hyphen exluded by default in regex matching? I mean this `exclude_from_prefix_regex = "-"`. 

For luadoc i changed it to `exclude_from_prefix_regex = "[\\.]"` and then [these snippets](https://github.com/rafamadriz/friendly-snippets/blob/efff286dd74c22f731cdec26a70b46e5b203c619/snippets/lua/luadoc.json#L2-L20) would appear with normal sorting. With the default exluding hyphen these snippets would appear right at the bottom of the completion menu, presumably because after the first hyphen no other hyphen is taken into consideration (if I'm understanding correctly but of course I could be wrong), thus making the score of these snippets not relevant to be on top would be my guess.
I also included `@` into `regex` otherwise snippets like `@author` would complete `@@author` and I had to just type `author` and then choose the `@author` snippet to only have one `@` after choosing the snippet.

@Saghen If you could give a bit more info on how `exclude_from_prefix_regex` operates that would be appreciated. I also tried to make it just an empty string `""`, but again the scores of those luadoc snippets didn't change and were at the bottom. Only putting some other character worked correctly. Is it safe for me to put `\\.` as a value instead of the default hyphen?

**Comment by idnsunset** [comment]
> Do you have `friendly-snippets` as a dependency? I'm not able to reproduce this

Yes, I have it. I'm using LazyVim with my own config for `blink.cmp`, but really has no clue about why this does not work.

**Comment by mdmjmsa** [comment]
> Do you have `friendly-snippets` as a dependency? I'm not able to reproduce this

I've encountered the same issue. I followed the suggestions from @dpetka2001 to remove `-` from `exclude_from_prefix_regex` and got the the luadoc snippets. However, I still cannot make the cppdoc snippets come up. Could you please attach your configuration used to try reproducing this issue?

**Comment by Saghen** [comment]
Sounds like this issue is a combination of #46 and #657

**Comment by madjxatw** [comment]
Does "Not planned" mean this issue won't be fixed at all? I am still suffering from it which is pretty annoying when I need to quickly insert doxygen style of docstrings for cpp code.
